apiVersion: v1
entries:
  kraken-ci:
  - annotations:
      artifacthub.io/license: Apache-2.0
    apiVersion: v2
    appVersion: "0.933"
    created: "2022-04-05T04:39:09.774403647Z"
    description: A Helm chart of Kraken CI for Kubernetes
    digest: ab83e1957630300afd962d07790e3c35c12d599a760c243212c21587005bd92f
    home: https://kraken.ci/
    icon: https://kraken.ci/img/logo-big2.svg
    keywords:
    - kraken-ci
    - continuous-integration
    - ci
    - cd
    - ci/cd
    - continuous-delivery
    - continuous-testing
    maintainers:
    - email: mike@kraken.ci
      name: Michal Nowikowski
    name: kraken-ci
    sources:
    - https://github.com/Kraken-CI/kraken
    type: application
    urls:
    - https://kraken.ci/helm-repo/charts/kraken-ci-0.933.0.tgz
    version: 0.933.0
  - annotations:
      artifacthub.io/license: Apache-2.0
    apiVersion: v2
    appVersion: "0.909"
    created: "2022-04-05T04:39:09.77295293Z"
    description: A Helm chart of Kraken CI for Kubernetes
    digest: 608928203740665c85070275604739457c2935af2a28163d892803ff4cec65f6
    home: https://kraken.ci/
    icon: https://kraken.ci/img/logo-big2.svg
    keywords:
    - kraken-ci
    - continuous-integration
    - ci
    - cd
    - ci/cd
    - continuous-delivery
    - continuous-testing
    maintainers:
    - email: mike@kraken.ci
      name: Michal Nowikowski
    name: kraken-ci
    sources:
    - https://github.com/Kraken-CI/kraken
    type: application
    urls:
    - https://kraken.ci/helm-repo/charts/kraken-ci-0.909.0.tgz
    version: 0.909.0
  - annotations:
      artifacthub.io/license: Apache-2.0
    apiVersion: v2
    appVersion: "0.888"
    created: "2022-04-05T04:39:09.771194387Z"
    description: A Helm chart of Kraken CI for Kubernetes
    digest: 6042026c7dc41e2c42a84cd001773821668c0ff9195a8e3ef348a8ac2ebe9148
    home: https://kraken.ci/
    icon: https://kraken.ci/img/logo-big2.svg
    keywords:
    - kraken-ci
    - continuous-integration
    - ci
    - cd
    - ci/cd
    - continuous-delivery
    - continuous-testing
    maintainers:
    - email: mike@kraken.ci
      name: Michal Nowikowski
    name: kraken-ci
    sources:
    - https://github.com/Kraken-CI/kraken
    type: application
    urls:
    - https://kraken.ci/helm-repo/charts/kraken-ci-0.888.0.tgz
    version: 0.888.0
generated: "2022-04-05T04:39:09.764383597Z"
